server:
  port: 8761                    # 指定该Eureka实例的端口
spring:
  application:
    name: eureka-sever
security:
  basic:
    enabled: true
  user: 
    name: llUSsXXR1ke23KBh
    password: JtOqja2DkSogUXG7   
eureka:
  server:
    enable-self-preservation: false
  instance:
    prefer-ip-address: true 
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://llUSsXXR1ke23KBh:JtOqja2DkSogUXG7@172.16.33.57:8761/eureka/

# 参考文档：http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#_standalone_mode
# 参考文档：http://my.oschina.net/buwei/blog/618756