server:
  port: 8762                   # 指定该Admin实例的端口
spring:
  application:
    name: admin-sever
  boot: 
    admin:
      client:
        metadata: 
          user.name: syplatform
          user.password: syplatform01
      monitor:
        period: 10000
      discovery: 
        enabled: true
security:
  user:
    name: syplatform
    password: syplatform01


management:
  security:
    enabled:  false
     
eureka:
  instance:
    metadata-map:
      user.name: syplatform
      user.password: syplatform01
    prefer-ip-address: true 
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://syplatform:syplatform01@localhost:8761/eureka/


info:
  owner: Lee
  version: 1.0
  
  